# Generated from the Omarchy palette. Keep the existing status layout.
set -g status-style 'fg={{ foreground }},bg={{ background }}'
set -g status-left '#[fg=#{?client_prefix,{{ red }},{{ foreground }}}] #[fg={{ foreground }}]#S  #[fg={{ muted }}] #[fg={{ accent }}]#W#[default]  '
set -g status-right ''
set -g message-style 'fg={{ foreground }},bg={{ lighter_background }}'
set -g message-command-style 'fg={{ background }},bg={{ accent }}'
set -g mode-style 'fg={{ selection_foreground }},bg={{ selection_background }}'
set -g pane-border-style 'fg={{ muted }}'
set -g pane-active-border-style 'fg={{ accent }}'
set -g window-status-style 'fg={{ foreground }},bg={{ background }}'
set -g window-status-current-style 'fg={{ accent }},bg={{ background }},bold'
set -g window-status-activity-style 'fg={{ background }},bg={{ yellow }}'
set -g window-status-bell-style 'fg={{ background }},bg={{ red }}'
set -g window-style 'fg={{ foreground }},bg={{ background }}'
set -g window-active-style 'fg={{ foreground }},bg={{ background }}'
set -g cursor-colour '{{ cursor }}'
