[tools]
bun = "latest"
claude = "latest"
cmake = "latest"
codex = "latest"
gh = "latest"
go = "latest"
helm = "latest"
node = "25.0.0"
python = "3.13"
ruby = "latest"
rust = "latest"
uv = "latest"
yarn = "1"
zig = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[settings.ruby]
compile = false
